export const AI_MAX_INPUT_TOKENS = 10_000;
export const AI_MAX_OUTPUT_TOKENS = 10_000;
export const AI_DEFAULT_MAX_OUTPUT_TOKENS = AI_MAX_OUTPUT_TOKENS;
export const AI_APPROXIMATE_CHARACTERS_PER_TOKEN = 4;
export const AI_MAX_INPUT_CHARACTERS =
  AI_MAX_INPUT_TOKENS * AI_APPROXIMATE_CHARACTERS_PER_TOKEN;

export const AI_PROVIDER_REQUEST_TIMEOUT_MS = 30_000;
export const AI_STREAM_TIMEOUT_MS = 10 * 60 * 1_000;
export const AI_STREAM_HEARTBEAT_MS = 15_000;
