export enum AiProtocol {
  OPENAI_RESPONSES = 'OPENAI_RESPONSES',
  OPENAI_CHAT_COMPLETIONS = 'OPENAI_CHAT_COMPLETIONS',
  ANTHROPIC_MESSAGES = 'ANTHROPIC_MESSAGES',
  GEMINI_GENERATE_CONTENT = 'GEMINI_GENERATE_CONTENT',
}
