import { Module } from '@nestjs/common';

import { PrismaModule } from '@/infrastructure/database';
import { AuthAuthorizationModule } from '@/modules/auth';
import { AuthorsModule } from '@/modules/authors';
import { CommentsModule } from '@/modules/comments';

import {
  ApproveStorySubmissionCommandHandler,
  CancelAuthorStorySubmissionCommandHandler,
  CHAPTER_PERSISTENCE_PORT,
  ClearReadingHistoryCommandHandler,
  CreateAuthorChapterCommandHandler,
  CreateAuthorStoryCommandHandler,
  CreateStoryCommentCommandHandler,
  DeleteAuthorChapterCommandHandler,
  DeleteAuthorStoryCommandHandler,
  DeleteStoryCommentCommandHandler,
  DeleteStoryRatingCommandHandler,
  GetAuthorChapterQueryHandler,
  GetAuthorStoryQueryHandler,
  GetMyStoryRatingQueryHandler,
  GetPublicChapterReaderQueryHandler,
  GetPublicStoryDetailQueryHandler,
  ListAuthorChaptersQueryHandler,
  ListAuthorStoriesQueryHandler,
  ListChapterCommentsQueryHandler,
  ListLibraryQueryHandler,
  ListPublicStoriesQueryHandler,
  ListReadingHistoryQueryHandler,
  ListStoryCategoriesQueryHandler,
  ListStoryCommentsQueryHandler,
  ListStoryTagsQueryHandler,
  PublishAuthorChapterCommandHandler,
  READER_ENGAGEMENT_PERSISTENCE_PORT,
  STORY_MODERATION_READER_PORT,
  RejectStorySubmissionCommandHandler,
  RemoveLibraryEntryCommandHandler,
  RemoveReadingHistoryEntryCommandHandler,
  SaveReadingProgressCommandHandler,
  STORY_PERSISTENCE_PORT,
  SubmitAuthorStoryCommandHandler,
  UpdateAuthorChapterCommandHandler,
  UpdateAuthorStoryCommandHandler,
  UpdateStoryCommentCommandHandler,
  UpsertLibraryEntryCommandHandler,
  UpsertStoryRatingCommandHandler,
} from './application';
import {
  PrismaChapterPersistence,
  PrismaReaderEngagementPersistence,
  PrismaStoryModerationReader,
  PrismaStoryPersistence,
} from './infrastructure';
import {
  AdminStoryModerationController,
  AdminStoryPublicationController,
  AuthorChaptersController,
  AuthorStoriesController,
  PublicStoriesController,
  PublicStoryCommentsController,
  ReaderEngagementController,
  StoryMetadataController,
} from './presentation/http';

@Module({
  imports: [PrismaModule, AuthAuthorizationModule, AuthorsModule, CommentsModule],
  controllers: [
    PublicStoriesController,
    PublicStoryCommentsController,
    ReaderEngagementController,
    AuthorStoriesController,
    AuthorChaptersController,
    StoryMetadataController,
    AdminStoryModerationController,
    AdminStoryPublicationController,
  ],
  providers: [
    CreateAuthorStoryCommandHandler,
    UpdateAuthorStoryCommandHandler,
    DeleteAuthorStoryCommandHandler,
    ListAuthorStoriesQueryHandler,
    GetAuthorStoryQueryHandler,
    CreateAuthorChapterCommandHandler,
    UpdateAuthorChapterCommandHandler,
    DeleteAuthorChapterCommandHandler,
    ListAuthorChaptersQueryHandler,
    GetAuthorChapterQueryHandler,
    PublishAuthorChapterCommandHandler,
    SubmitAuthorStoryCommandHandler,
    CancelAuthorStorySubmissionCommandHandler,
    ApproveStorySubmissionCommandHandler,
    RejectStorySubmissionCommandHandler,
    ListPublicStoriesQueryHandler,
    GetPublicStoryDetailQueryHandler,
    GetPublicChapterReaderQueryHandler,
    ListStoryCategoriesQueryHandler,
    ListStoryTagsQueryHandler,
    ListLibraryQueryHandler,
    UpsertLibraryEntryCommandHandler,
    RemoveLibraryEntryCommandHandler,
    ListReadingHistoryQueryHandler,
    SaveReadingProgressCommandHandler,
    RemoveReadingHistoryEntryCommandHandler,
    ClearReadingHistoryCommandHandler,
    GetMyStoryRatingQueryHandler,
    UpsertStoryRatingCommandHandler,
    DeleteStoryRatingCommandHandler,
    ListStoryCommentsQueryHandler,
    ListChapterCommentsQueryHandler,
    CreateStoryCommentCommandHandler,
    UpdateStoryCommentCommandHandler,
    DeleteStoryCommentCommandHandler,
    PrismaStoryPersistence,
    PrismaChapterPersistence,
    PrismaReaderEngagementPersistence,
    PrismaStoryModerationReader,
    {
      provide: STORY_PERSISTENCE_PORT,
      useExisting: PrismaStoryPersistence,
    },
    {
      provide: CHAPTER_PERSISTENCE_PORT,
      useExisting: PrismaChapterPersistence,
    },
    {
      provide: READER_ENGAGEMENT_PERSISTENCE_PORT,
      useExisting: PrismaReaderEngagementPersistence,
    },
    {
      provide: STORY_MODERATION_READER_PORT,
      useExisting: PrismaStoryModerationReader,
    },
  ],
})
export class StoriesModule {}
