export const AUTH_ENDPOINTS = {
  register: '/auth/register',
  login: '/auth/login',
  refresh: '/auth/refresh',
  logout: '/auth/logout',
  logoutAll: '/auth/logout-all',
  revokeAccessToken: '/auth/revoke-access-token',
  verifyEmail: '/auth/verify-email',
  resendVerification: '/auth/resend-verification',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  changePassword: '/auth/change-password',
  requestEmailChange: '/auth/change-email',
  confirmEmailChange: '/auth/change-email/confirm',
  currentUser: '/auth/me',
  sessions: '/auth/sessions',
  securityEvents: '/auth/security-events',
} as const;
