export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
  CURSOR_LIMIT: 20,
  MAX_CURSOR_LIMIT: 100,
} as const;

export const DEFAULT_PAGE = PAGINATION_DEFAULTS.PAGE;
export const DEFAULT_PAGE_LIMIT = PAGINATION_DEFAULTS.LIMIT;
export const MAX_PAGE_LIMIT = PAGINATION_DEFAULTS.MAX_LIMIT;
export const DEFAULT_CURSOR_LIMIT = PAGINATION_DEFAULTS.CURSOR_LIMIT;
export const MAX_CURSOR_LIMIT = PAGINATION_DEFAULTS.MAX_CURSOR_LIMIT;
