export const MILLISECONDS_PER_SECOND = 1_000;
export const SECONDS_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;

export const SECOND_IN_MS = MILLISECONDS_PER_SECOND;
export const MINUTE_IN_MS = SECONDS_PER_MINUTE * SECOND_IN_MS;
export const HOUR_IN_MS = MINUTES_PER_HOUR * MINUTE_IN_MS;
export const DAY_IN_MS = HOURS_PER_DAY * HOUR_IN_MS;

export const MINUTE_IN_SECONDS = SECONDS_PER_MINUTE;
export const HOUR_IN_SECONDS = MINUTES_PER_HOUR * MINUTE_IN_SECONDS;
export const DAY_IN_SECONDS = HOURS_PER_DAY * HOUR_IN_SECONDS;
